### ISSUE TITLE
Improve Shortened Link Functionality with Subpath Access

### ISSUE THREAD

**Issue by delvdeepr** [Jeusto/1pt.one#1]
I guarantee an enhanced experience if the shortened link allows clients to access specific subpaths.

For example, by shortening the URL <https://github.com> to `1pt.one/3VFA`, users can append subpaths like <https://1pt.one/3VFA/creuserr> to directly reach `github.com/creuserr`.

**Comment by Jeusto** [comment]
Thanks for the suggestion. I just added with the commit 3305198f60d6ae44a328ccc5878fd2138bbdec50. 

For example, [1pt.one/gh/jeusto](https://1pt.one/gh/jeusto) now redirects to [github.com/jeusto](https://github.com/Jeusto). Let me know if it works as expected
